- name: "Start awx server"
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars.yml
  tasks:
  - name: "Check if awx is already cloned"
    stat:
      path: "{{ awx_location }}"
    register: awx_cloned

#  - name: "Start AWX"
#    command: ansible-playbook -i inventory install.yml
#    args:
#      chdir: "{{ awx_location }}/installer"
#    when: awx_cloned.stat.exists
  - name: "Start nginx reverse-proxy for https"
    docker_container:
      name: nginx-reverse-proxy
      image: nginx
      volumes:
        - "{{ playbook_dir }}/files/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
        - "{{ playbook_dir }}/keys/nginx:/etc/nginx/ssl"
      ports:
        - 443:443
      links:
        - "awx_web:awxweb"
      state: started
    when: awx_cloned.stat.exists
