- name: "Setup file"
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars.yml
  tasks:
  - name: "Look for PoC file"
    stat: 
      path: "{{ playbook_dir }}/projects/RPIProject/sendsensorsdata.py"
    register: pocFile
  - debug: var=pocFile
  - name: "Set PG_HOST"
    lineinfile:
      path: "{{ playbook_dir }}/projects/RPIProject/sendsensorsdata.py"
      regexp: "^PG_HOST =.*"
      line: "PG_HOST = \"192.168.1.333\""
      state: present
    when: pocFile.stat.exists
  - name: "Set PG_PASSWORD"
    lineinfile:
      path: "{{ playbook_dir }}/projects/RPIProject/sendsensorsdata.py"
      regexp: "^PG_PASSWORD =.*"
      line: "PG_PASSWORD = \"{{ pg_sensors_password }}\""
      state: present
    when: pocFile.stat.exists
  - name: "Set PG_DATABASE"
    lineinfile:
      path: "{{ playbook_dir }}/projects/RPIProject/sendsensorsdata.py"
      regexp: "^PG_DATABASE =.*"
      line: "PG_DATABASE = \"{{ pg_sensors_database }}\""
      state: present
    when: pocFile.stat.exists
  - name: "Set PG_USERNAME"
    lineinfile:
      path: "{{ playbook_dir }}/projects/RPIProject/sendsensorsdata.py"
      regexp: "^PG_USERNAME =.*"
      line: "PG_USERNAME = \"{{ pg_sensors_username }}\""
      state: present
    when: pocFile.stat.exists
  - name: "Set PG_PORT"
    lineinfile:
      path: "{{ playbook_dir }}/projects/RPIProject/sendsensorsdata.py"
      regexp: "^PG_PORT =.*"
      line: "PG_PORT = \"{{ pg_sensors_port }}\""
      state: present
    when: pocFile.stat.exists



    
